# 1. 경로 / 저장 관련
config: configs/maetok-b-64.yaml
results_dir: experiments/tokenizer
cloud_save_path: experiments/tokenizer
data_path: tiny-imagenet-200/train   # CLI override
dataset: imagenet
no_local_save: True
exp_index: None

# 2. 실험 제어 / 공통 옵션
compile: False
global_seed: 42
global_batch_size: 32                # CLI override
num_workers: 16
mixed_precision: bf16
log_every: 50
vis_every: 5000
ckpt_every: 10000
gradient_accumulation_steps: 1

# 3. 학습 스케줄 / 최적화
epochs: 200
optimizer: adamw
lr: 1.0e-4
lr_scheduler: cosine
lr_warmup_epochs: 2
weight_decay: 0.0001
beta1: 0.9
beta2: 0.95
max_grad_norm: 1.0

# 4. 모델 기본 설정
vq_model: MaskAE-16
vq_ckpt: None
finetune: False
ema: True

# 5. VQ / Codebook
codebook_size: 16384
codebook_embed_dim: 32
codebook_l2_norm: True
codebook_weight: 1.0
entropy_loss_ratio: 0.0
vq_loss_ratio: 1.0
commit_loss_beta: 0.25
num_codebooks: 1
tau: 0.1

# 6. Reconstruction & Loss
reconstruction_loss: l2
reconstruction_weight: 1.0
kl_loss_weight: 0.000001
perceptual_loss: vgg
perceptual_model: vgg
perceptual_weight: 1.0
perceptual_dino_variants: depth12_no_train
perceptual_intermediate_loss: False
perceptual_logit_loss: False
perceptual_resize: False
perceptual_warmup: 10000


























# 7. Discriminator / GAN 관련
disc_weight: 0.4
disc_start: 30000
disc_dim: 64
disc_type: dino
disc_loss: hinge
gen_loss: hinge
lecam_loss_weight: 0.001
use_diff_aug: True
disc_cr_loss_weight: 4.0
disc_adaptive_weight: True

# 8. Encoder / Decoder 구조
enc_type: vit
dec_type: vit
encoder_model: vit_base_patch14_dinov2.lvd142m
decoder_model: vit_base_patch14_dinov2_movqv2
encoder_tuning_method: full
decoder_tuning_method: full
encoder_pretrained: False
decoder_pretrained: False
encoder_patch_size: 16
decoder_patch_size: 16
decoder_drop_path_rate: 0.05
decoder_cls_token: False
to_pixel: linear
image_size: 256                     # CLI override
dropout_p: 0.0

# 9. Tokenizer / Mask 관련
num_latent_tokens: 128
enc_token_drop: 0.4
enc_token_drop_max: 0.6

# 10. Positional Encoding
use_ape: False
use_rope: True
rope_mixed: True
rope_theta: 10.0

# 11. Aux Decoder
aux_decoder_model: vit_tinytiny_patch14_dinov2_movq2
aux_loss_mask: True
aux_hog_decoder: True
aux_dino_decoder: True
aux_clip_decoder: True
aux_supcls_decoder: True

# 12. REPA (representation alignment)
repa: True
repa_model: vit_large_patch14_dinov2.lvd142m
repa_patch_size: 16
repa_proj_dim: 1024
repa_loss_weight: 0.1
repa_align: repeat

